#!/usr/bin/env python
"""No AI authorship in commit, tag, or PR metadata. Deep dive P0 section 4.3.

**The goal is that no commit, PR, or tag is *authored by* an AI. It is NOT to
purge the word "Claude" from the repository.** Those are different things, and
conflating them creates an unwinnable loop: `.gitignore` must contain the literal
`CLAUDE.md`, a docstring may legitimately reference a vendor API, and the next
legitimate mention trips the checker again. DE-000l records that loop being hit,
and the corrected scope exists so it is not re-derived.

So this scans **authorship metadata only** -- author and committer identity, the
commit-message trailer block, and tag taggers -- across the full history. File
contents are topic, not attribution, and are none of this checker's business.

The one content-adjacent check that remains is narrow and unambiguous: `CLAUDE.md`
and `.claude/` must be absent from *tracked files*. That is a check on what is
committed, not on what words appear inside committed files, and it closes a
genuine signature leak without pretending a word is contraband.

Acquisition and judgement are separated deliberately. `scan_authorship_metadata`
is the judge and is identical on both paths; only the source of the records
differs, so a planted fixture and the real history are graded by the same code.
The git-reading path is covered by running this checker over the real repository,
which is the full-history requirement in section 12 and not a second-best.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

# Section 4.3, and banned in metadata fields ONLY. Case-insensitive.
BANNED_TOKENS: tuple[str, ...] = (
    "claude",
    "anthropic",
    "openai",
    "copilot",
    "chatgpt",
    "gpt-4",
    "gemini",
    "cursor",
    "generated with",
    "generated by",
    "assisted by",
    "ai-generated",
    "co-authored-by: ai",
    "noreply@anthropic",
    "\N{ROBOT FACE}",
)

# Committing either is the loudest signature there is (section 4.4).
FORBIDDEN_TRACKED = ("CLAUDE.md", ".claude/", ".claude")

# One record per commit. Field order matches `parse_git_history`.
GIT_LOG_FORMAT = "%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%(trailers:only,unfold)%x1e"

FIXTURE_HISTORY = "FIXTURE_GIT_LOG"


@dataclass(frozen=True)
class Commit:
    """The authorship metadata of one commit or tag. Never its file contents."""

    sha: str
    author_name: str
    author_email: str
    committer_name: str
    committer_email: str
    trailers: str

    def fields(self) -> dict[str, str]:
        return {
            "author name": self.author_name,
            "author email": self.author_email,
            "committer name": self.committer_name,
            "committer email": self.committer_email,
            "trailers": self.trailers,
        }


@dataclass
class Report:
    findings: list[str] = field(default_factory=list)
    commits_scanned: int = 0

    @property
    def ok(self) -> bool:
        return not self.findings


class AttributionError_(RuntimeError):
    """The checker cannot run. Distinct from the checker finding a violation."""


def _git(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )


def scan_authorship_metadata(commits: list[Commit]) -> list[str]:
    """Judge a sequence of authorship records. Section 4.3.

    The whole of the checker's opinion lives here, and it is deliberately the
    only part that judges: acquisition is separate so that a planted fixture and
    the real history are graded by identical code. A checker whose test path and
    production path diverge is certifying the test path.

    Note what is *not* inspected: the commit message body. A message may
    legitimately say "fix the Claude API client" -- that is topic. The trailer
    block is where authorship is asserted, and that is what is read.
    """
    findings: list[str] = []
    for commit in commits:
        for label, value in commit.fields().items():
            lowered = value.lower()
            for token in BANNED_TOKENS:
                if token in lowered:
                    findings.append(
                        f"{commit.sha[:12]}: {label} carries {token!r} -- "
                        f"authorship attribution ({value.strip()!r})"
                    )
    return findings


def parse_git_history(raw: str) -> list[Commit]:
    """Parse `git log --format=GIT_LOG_FORMAT` output into records."""
    commits: list[Commit] = []
    for record in raw.split("\x1e"):
        cleaned = record.strip("\n")
        if not cleaned.strip():
            continue
        parts = cleaned.split("\x1f")
        if len(parts) < 6:
            parts += [""] * (6 - len(parts))
        commits.append(
            Commit(
                sha=parts[0].strip(),
                author_name=parts[1],
                author_email=parts[2],
                committer_name=parts[3],
                committer_email=parts[4],
                trailers=parts[5],
            )
        )
    return commits


def parse_fixture_history(text: str) -> list[Commit]:
    """Parse the reviewable fixture form: `key: value` blocks, blank-line separated.

    A fixture whose contents are control-character-delimited cannot be read by a
    reviewer, and a planted violation nobody can read is a planted violation
    nobody can check. The records this produces are the same `Commit` objects
    `parse_git_history` produces, and both are handed to the same judge.
    """
    commits: list[Commit] = []
    for block in text.split("\n\n"):
        values: dict[str, str] = {}
        for line in block.splitlines():
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            key, _, value = line.partition(":")
            values[key.strip().lower()] = value.strip()
        if not values:
            continue
        commits.append(
            Commit(
                sha=values.get("sha", "0" * 40),
                author_name=values.get("author", ""),
                author_email=values.get("author_email", ""),
                committer_name=values.get("committer", ""),
                committer_email=values.get("committer_email", ""),
                trailers=values.get("trailers", ""),
            )
        )
    return commits


def read_history(root: Path) -> list[Commit]:
    """Full history from git, or from the fixture seam in a tree that has no git.

    As in `check_spec_isolation`, the seam is unreachable wherever a `.git`
    exists, so dropping a FIXTURE_GIT_LOG into the real repository accomplishes
    nothing.
    """
    if (root / ".git").exists():
        result = _git(root, "log", "--all", f"--format={GIT_LOG_FORMAT}")
        if result.returncode != 0:
            raise AttributionError_(f"cannot read history in {root}: {result.stderr.strip()}")
        commits = parse_git_history(result.stdout)

        tags = _git(root, "for-each-ref", "--format=%(refname)%x1f%(taggername)%x1f%(taggeremail)")
        for line in tags.stdout.splitlines():
            if not line.strip():
                continue
            parts = line.split("\x1f")
            if len(parts) < 3 or not parts[1].strip():
                continue
            commits.append(
                Commit(
                    sha=parts[0],
                    author_name=parts[1],
                    author_email=parts[2],
                    committer_name=parts[1],
                    committer_email=parts[2],
                    trailers="",
                )
            )
        return commits

    fixture = root / FIXTURE_HISTORY
    if not fixture.exists():
        raise AttributionError_(
            f"{root} is not a git repository and carries no {FIXTURE_HISTORY}; "
            "there is no history to scan, and no history is not a clean history"
        )
    return parse_fixture_history(fixture.read_text(encoding="utf-8"))


def scan_tracked_paths(root: Path) -> list[str]:
    """Assert the tool's own config never entered the public history. Section 4.4."""
    if not (root / ".git").exists():
        return []
    result = _git(root, "ls-files")
    if result.returncode != 0:
        return []
    findings = []
    for path in result.stdout.splitlines():
        normalised = path.strip().replace("\\", "/")
        if normalised.startswith(FORBIDDEN_TRACKED) or normalised == "CLAUDE.md":
            findings.append(
                f"{normalised} is tracked. It is gitignored for a reason "
                "(section 4.4): a committed tool config is a signature leak"
            )
    return findings


def check(root: Path) -> Report:
    """Scan the full history plus the tracked-path rule."""
    commits = read_history(root)
    report = Report(commits_scanned=len(commits))
    report.findings.extend(scan_authorship_metadata(commits))
    report.findings.extend(scan_tracked_paths(root))
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Attribution (deep dive P0 section 4.3).")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    args = parser.parse_args(argv)

    try:
        report = check(args.root)
    except AttributionError_ as exc:
        print(f"check_attribution: REFUSED TO RUN: {exc}", file=sys.stderr)
        return 2

    if report.findings:
        for finding in report.findings:
            print(f"  FAIL  {finding}", file=sys.stderr)
        print(f"check_attribution: {len(report.findings)} finding(s)", file=sys.stderr)
        return 1

    print(f"check_attribution: clean over {report.commits_scanned} record(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
